"""Hashline: content-hash anchors for file line editing.

Inspired by oh-my-pi's hashline edit format. Each line gets a
2-char hash anchor that serves as both an address and a staleness
check.

Format: ``{line_number}#{hash}:{original_line}``
Example: ``42#RK: def foo(self):``

Uses Elixir acceleration when available (via HashlineNif through JSON-RPC),
falls back to a pure Python implementation that uses ``zlib.crc32``.

Routing priority: Elixir -> Python

.. warning::
    The Python fallback uses ``zlib.crc32`` rather than ``xxHash32``,
    so its hash values are **not compatible** with those produced by
    the Elixir backend. Both variants still provide reliable
    staleness detection; you just cannot mix anchors generated by
    one backend with a validator running the other backend.
"""

from __future__ import annotations

import re
import zlib
from typing import Any

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

NIBBLE_STR = "ZPMQVRWSNKTXJBYH"

# ---------------------------------------------------------------------------
# Regex for stripping hashline prefixes
# ---------------------------------------------------------------------------

_HASHLINE_PREFIX_RE = re.compile(r"^\d+#[A-Z]{2}:(.*)", re.DOTALL)

# ---------------------------------------------------------------------------
# Backend-mixing guard (shepherd review MUST-FIX #1)
# ---------------------------------------------------------------------------

# Tracks whether any Elixir hash operation has ever succeeded in this process.
# Once True, validate_hashline_anchor MUST use Elixir (or raise) -- falling
# back to Python would silently produce wrong results because the hash
# algorithms (xxHash32 vs zlib.crc32) are incompatible.
_ELIXIR_HASH_USED: bool = False

# ---------------------------------------------------------------------------
# Elixir routing helpers
# ---------------------------------------------------------------------------


def _get_transport() -> Any | None:
    """Get the Elixir transport singleton if available.

    Returns None if transport is not available (Elixir not running).
    """
    try:
        from code_puppy.elixir_transport_helpers import get_transport

        return get_transport()
    except Exception:
        return None


def _try_elixir_compute_line_hash(idx: int, line: str) -> str | None:
    """Try Elixir hashline_compute, return None on failure.

    Wired to Elixir transport hashline_compute method.
    Returns hash string on success, None on any exception.
    """
    global _ELIXIR_HASH_USED
    transport = _get_transport()
    if transport is None:
        return None
    try:
        result = transport._send_request(
            "hashline_compute",
            {
                "idx": idx,
                "line": line,
            },
        )
        _ELIXIR_HASH_USED = True
        return result.get("hash")
    except Exception:
        return None


def _try_elixir_format_hashlines(text: str, start_line: int) -> str | None:
    """Try Elixir hashline_format, return None on failure.

    Wired to Elixir transport hashline_format method.
    Returns formatted string on success, None on any exception.
    """
    global _ELIXIR_HASH_USED
    transport = _get_transport()
    if transport is None:
        return None
    try:
        result = transport._send_request(
            "hashline_format",
            {
                "text": text,
                "start_line": start_line,
            },
        )
        _ELIXIR_HASH_USED = True
        return result.get("formatted")
    except Exception:
        return None


def _try_elixir_strip_hashline_prefixes(text: str) -> str | None:
    """Try Elixir hashline_strip, return None on failure.

    Wired to Elixir transport hashline_strip method.
    Returns stripped string on success, None on any exception.

    NOTE: strip_hashline_prefixes does NOT set _ELIXIR_HASH_USED because
    stripping is a pure string operation with no hash compatibility concern.
    """
    transport = _get_transport()
    if transport is None:
        return None
    try:
        result = transport._send_request(
            "hashline_strip",
            {
                "text": text,
            },
        )
        return result.get("stripped")
    except Exception:
        return None


def _try_elixir_validate_hashline_anchor(
    idx: int, line: str, expected_hash: str
) -> bool | None:
    """Try Elixir hashline_validate, return None on failure.

    Wired to Elixir transport hashline_validate method.
    Returns bool on success, None on any exception.
    """
    global _ELIXIR_HASH_USED
    transport = _get_transport()
    if transport is None:
        return None
    try:
        result = transport._send_request(
            "hashline_validate",
            {
                "idx": idx,
                "line": line,
                "expected_hash": expected_hash,
            },
        )
        _ELIXIR_HASH_USED = True
        return result.get("valid")
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Pure-Python fallback implementations
# ---------------------------------------------------------------------------


def _py_compute_line_hash(idx: int, line: str) -> str:
    """Pure-Python fallback using ``zlib.crc32`` instead of xxHash32.

    The algorithm mirrors the Elixir NIF version except the hash primitive:
    - Strip trailing whitespace / ``\\r``
    - If no alphanumeric characters: seed = idx, else seed = 0
    - ``zlib.crc32(bytes, seed) & 0xFF`` -> encode low byte via NIBBLE_STR

    .. note::
        Hash values produced here are NOT compatible with those from the
        Elixir implementation (which uses xxHash32).
    """
    # Strip trailing whitespace and \\r
    cleaned = line.rstrip("\r \t\n\x0b\x0c")

    has_alnum = any(c.isalnum() for c in cleaned)
    seed = 0 if has_alnum else idx

    # zlib.crc32 uses a running checksum; passing seed as starting value
    # gives us per-line differentiation for blank/punctuation lines.
    raw = zlib.crc32(cleaned.encode("utf-8"), seed) & 0xFFFFFFFF

    byte = raw & 0xFF
    hi = NIBBLE_STR[(byte >> 4) & 0xF]
    lo = NIBBLE_STR[byte & 0xF]
    return hi + lo


def _py_format_hashlines(text: str, start_line: int = 1) -> str:
    """Pure-Python fallback for :func:`format_hashlines`."""
    parts: list[str] = []
    for i, line in enumerate(text.split("\n")):
        line_num = start_line + i
        h = _py_compute_line_hash(line_num, line)
        parts.append(f"{line_num}#{h}:{line}")
    return "\n".join(parts)


def _py_strip_hashline_prefixes(text: str) -> str:
    """Pure-Python fallback for :func:`strip_hashline_prefixes`."""
    result: list[str] = []
    for line in text.split("\n"):
        m = _HASHLINE_PREFIX_RE.match(line)
        result.append(m.group(1) if m else line)
    return "\n".join(result)


def _py_validate_hashline_anchor(idx: int, line: str, expected_hash: str) -> bool:
    """Pure-Python fallback for :func:`validate_hashline_anchor`."""
    return _py_compute_line_hash(idx, line) == expected_hash


# ---------------------------------------------------------------------------
# Public API (dispatch to Elixir or Python depending on availability)
# ---------------------------------------------------------------------------


def compute_line_hash(idx: int, line: str) -> str:
    """Return a 2-character hash anchor for *line* at 1-based index *idx*.

    The returned string consists of two uppercase characters drawn from
    :data:`NIBBLE_STR`.

    Routing priority: Elixir -> Python

    Args:
        idx: 1-based line number used as the hash seed for
              blank/punctuation-only lines.
        line: Raw line content (trailing whitespace is ignored).

    Returns:
        Two-character uppercase hash string, e.g. ``"RK"``.
    """
    # Try Elixir first
    elixir_result = _try_elixir_compute_line_hash(idx, line)
    if elixir_result is not None:
        return elixir_result
    return _py_compute_line_hash(idx, line)


def format_hashlines(text: str, start_line: int = 1) -> str:
    """Prefix every line in *text* with a hashline anchor.

    Each line becomes ``{line_number}#{hash}:{original_line}``.

    Routing priority: Elixir -> Python

    Args:
        text: Multi-line string to annotate.
        start_line: 1-based number of the first line (default ``1``).

    Returns:
        Annotated text with the same number of lines as *text*.
    """
    # Try Elixir first
    elixir_result = _try_elixir_format_hashlines(text, start_line)
    if elixir_result is not None:
        return elixir_result
    return _py_format_hashlines(text, start_line)


def strip_hashline_prefixes(text: str) -> str:
    """Remove hashline prefixes from *text*, returning the plain content.

    Lines that do NOT match the ``^\\d+#[A-Z]{2}:`` pattern pass through
    unchanged, so it is safe to call this on partially-annotated text.

    Routing priority: Elixir -> Python

    Args:
        text: Text that may contain hashline-prefixed lines.

    Returns:
        Text with all hashline prefixes removed.
    """
    # Try Elixir first
    elixir_result = _try_elixir_strip_hashline_prefixes(text)
    if elixir_result is not None:
        return elixir_result
    return _py_strip_hashline_prefixes(text)


def validate_hashline_anchor(idx: int, line: str, expected_hash: str) -> bool:
    """Check whether *expected_hash* still matches *line* at index *idx*.

    Returns ``True`` if the content is unchanged; ``False`` if the line
    has been modified since the anchor was recorded (staleness detected).

    Routing priority: Elixir -> Python

    Args:
        idx: 1-based line number (same value used when the
                       anchor was originally computed).
        line: Current line content.
        expected_hash: 2-character hash string to compare against.

    Returns:
        ``True`` if the hashes agree, ``False`` otherwise.

    Raises:
        RuntimeError: If Elixir hashes were used previously but the Elixir
                      backend is now unavailable. Falling back to Python
                      in this case would silently produce wrong results
                      because xxHash32 != zlib.crc32.
    """
    # Try Elixir first
    elixir_result = _try_elixir_validate_hashline_anchor(idx, line, expected_hash)
    if elixir_result is not None:
        return elixir_result

    # Shepherd review MUST-FIX #1: If Elixir was used for hashing but is now
    # unavailable, we MUST NOT fall back to Python (incompatible algorithms).
    if _ELIXIR_HASH_USED:
        raise RuntimeError(
            "Elixir backend was used for hashing but is now unavailable. "
            "Cannot validate because Python (zlib.crc32) and Elixir (xxHash32) "
            "produce incompatible hash values."
        )
    return _py_validate_hashline_anchor(idx, line, expected_hash)


def is_using_elixir() -> bool:
    """Return ``True`` if the Elixir acceleration is active for this module.

    Returns True when the Elixir transport is accessible.
    When True, hashline operations will route to the Elixir backend
    which uses xxHash32 (not compatible with Python's zlib.crc32).

    Returns True if transport is available, False otherwise.
    """
    return _get_transport() is not None
